### ISSUE TITLE
kube-keepalived-vip 是否支持动态修改 vip-configmap？

### ISSUE THREAD

**Issue by JinsYin** [kweisamx/kubernetes-keepalived-vip#2]
@kweisamx 
你好，请问一下 `kube-keepalived-vip` 是否支持动态修改 vip-configmap，比如添加或删除 Service。我目前的 kubernetes 1.8 版本测试发现并不支持，因此想确认一下。

**Comment by kweisamx** [comment]
HI @JinsYin 
 `kube-keepalived-vip` 不支持喔

兩種作法, 
1. 結合 kube-keepalived-vip 與 ingress , 但是要使用domain name
2. 一開始就先把對應的service 設定在vip-configmap 例如先寫入service1~service 100
然後在create service 時用service 1 ~ service 100 即可自動對應 , 但缺點就是service name無法改以及一開始列出多少就只能用多少IP

或是update 整個 `kube-keepalived-vip`  但是就會有downtime
給您參考

**Comment by JinsYin** [comment]
Thx.

我实际测试发现可以间接更新 vip-configmap，步骤如下：
  1. 修改 vip-configmap，比如添加或删除 Service；
  2. 修改 keepalived 默认配置中的 Service，比如修改 Service Port，甚至修改 `SVC.spec.ports[*].name` 也可以让 kube-keepalived-vip 自动更新配置。

以上操作非常奇怪，总感觉是个 bug，但相对于你提到的做法 2 要灵活些。

另外，请问下 kube-keepalived-vip 如何与 ingress 结合？

**Comment by kweisamx** [comment]
@JinsYin 
是的你的操作會自動更新應該不是正規的手法, 這邊我也不保證它可以跑在production環境

結合的部份就是讓 kube-keepalived-vip 去對應到 ingress service 
這篇[slide](https://www.slideshare.net/WeiShengZheng/kubernetes-service-with-ha) 是我在kubernetes 技術討論上的分享
第23頁就是示意圖 供您參考

**Comment by JinsYin** [comment]
抱歉，还是没太看明白。

我常用的做法是 keepalived + nginx-ingress-controller --> ingress/tcp service/udp service。如果可以 kube-keepalived-vip + ingress 的话，它的性能会更好？谢谢

**Comment by kweisamx** [comment]
@JinsYin 沒關係 我找時間在寫一些相關教學
主要是如果直接用keepalived + nginx-ingress-controller 安裝手續複雜限制也比較多 用keepalived可以省事並且擴充性高 當然效能上可能有一些些得損失

**Comment by JinsYin** [comment]
@kweisamx O(∩_∩)O谢谢
